apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: omnibrary-com-tls
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: libista.com
  dnsNames:
    - omnibrary.com
    - www.omnibrary.com
    - api.omnibrary.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - omnibrary.com
          - www.omnibrary.com
